name: iterative-labelling
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=20.1.0=py38h9ed2024_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.15.0=py38hc55c11b_1
  - debugpy=1.5.1=py38he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - ffmpeg=4.3=h0a44026_0
  - freetype=2.11.0=hd8bbffd_0
  - gettext=0.21.0=h7535e17_0
  - giflib=5.2.1=haf1e3a3_0
  - gmp=6.2.1=h23ab428_2
  - gnutls=3.6.15=hed9c0bf_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=4.8.2=py38hecd8cb5_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - iniconfig=1.1.1=py_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.4.1=py38hecd8cb5_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py38hecd8cb5_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - lame=3.100=h1de35cc_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libiconv=1.16=h1de35cc_0
  - libidn2=2.3.2=h9ed2024_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtasn1=4.16.0=h9ed2024_0
  - libtiff=4.2.0=h87d7836_0
  - libunistring=0.9.10=h9ed2024_0
  - libuv=1.40.0=haf1e3a3_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - libxml2=2.9.12=hcdb78fc_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - lz4-c=1.9.3=h23ab428_1
  - markupsafe=2.0.1=py38h9ed2024_0
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.1=py38h4ab4a9b_0
  - mkl_random=1.2.2=py38hb2f4e1b_0
  - more-itertools=8.5.0=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py38hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=h230ac6f_1
  - notebook=6.4.6=py38hecd8cb5_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h8346a28_0
  - openssl=1.1.1m=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38hecd8cb5_0
  - pluggy=0.13.1=py38_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.9.0=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py38hca72f7f_0
  - pytest=6.1.1=py38_0
  - python=3.8.12=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.2=py3.8_0
  - pyzmq=22.3.0=py38he9d5cce_2
  - readline=8.1.2=hca72f7f_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38hecd8cb5_0
  - sqlite=3.37.0=h707629a_0
  - terminado=0.9.4=py38hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h7bc2e8c_0
  - toml=0.10.1=py_0
  - torchaudio=0.10.2=py38_cpu
  - torchvision=0.11.3=py38_cpu
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h4dc903c_4
  - zstd=1.4.9=h322a384_0
  - pip:
    - absl-py==0.15.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - audioread==2.1.9
    - black==21.12b0
    - cachetools==5.0.0
    - charset-normalizer==2.0.7
    - click==8.0.3
    - configparser==5.1.0
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - executing==0.8.2
    - flatbuffers==1.12
    - fonttools==4.28.2
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.3
    - imagecodecs==2021.11.20
    - imageio==2.11.1
    - ipython==8.0.0
    - joblib==1.1.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - llvmlite==0.38.0
    - markdown==3.3.6
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - numba==0.55.1
    - numpy==1.19.5
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - pandas==1.4.1
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pillow==8.4.0
    - platformdirs==2.4.1
    - promise==2.3
    - prompt-toolkit==3.0.24
    - protobuf==3.19.1
    - psutil==5.8.0
    - pure-eval==0.2.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.11.2
    - pyparsing==3.0.6
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.1
    - python-dotenv==0.19.2
    - pytz==2022.1
    - pywavelets==1.2.0
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - resampy==0.2.2
    - rsa==4.8
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - scipy==1.7.2
    - sentry-sdk==1.5.0
    - setproctitle==1.2.3
    - setuptools-scm==6.3.2
    - shortuuid==1.0.8
    - six==1.15.0
    - smmap==5.0.0
    - soundfile==0.9.0
    - stack-data==0.1.3
    - subprocess32==3.5.4
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.5.2
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==1.2.2
    - tqdm==4.28.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - wandb==0.12.16
    - wave==0.0.2
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - yaspin==2.1.0
prefix: /Users/shefalibagaria/opt/anaconda3/envs/wekatest
